// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/analytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_SearchEvents_FullMethodName           = "/analytics.v1.AnalyticsService/SearchEvents"
	AnalyticsService_GetRegistrationsReport_FullMethodName = "/analytics.v1.AnalyticsService/GetRegistrationsReport"
	AnalyticsService_GetLoginReport_FullMethodName         = "/analytics.v1.AnalyticsService/GetLoginReport"
	AnalyticsService_GetTopUsersReport_FullMethodName      = "/analytics.v1.AnalyticsService/GetTopUsersReport"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	GetRegistrationsReport(ctx context.Context, in *ReportPeriodRequest, opts ...grpc.CallOption) (*RegistrationsReportResponse, error)
	GetLoginReport(ctx context.Context, in *ReportPeriodRequest, opts ...grpc.CallOption) (*LoginReportResponse, error)
	GetTopUsersReport(ctx context.Context, in *TopUsersReportRequest, opts ...grpc.CallOption) (*TopUsersReportResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRegistrationsReport(ctx context.Context, in *ReportPeriodRequest, opts ...grpc.CallOption) (*RegistrationsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationsReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRegistrationsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetLoginReport(ctx context.Context, in *ReportPeriodRequest, opts ...grpc.CallOption) (*LoginReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLoginReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopUsersReport(ctx context.Context, in *TopUsersReportRequest, opts ...grpc.CallOption) (*TopUsersReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopUsersReportResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopUsersReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	GetRegistrationsReport(context.Context, *ReportPeriodRequest) (*RegistrationsReportResponse, error)
	GetLoginReport(context.Context, *ReportPeriodRequest) (*LoginReportResponse, error)
	GetTopUsersReport(context.Context, *TopUsersReportRequest) (*TopUsersReportResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRegistrationsReport(context.Context, *ReportPeriodRequest) (*RegistrationsReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistrationsReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLoginReport(context.Context, *ReportPeriodRequest) (*LoginReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoginReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopUsersReport(context.Context, *TopUsersReportRequest) (*TopUsersReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopUsersReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRegistrationsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRegistrationsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRegistrationsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRegistrationsReport(ctx, req.(*ReportPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetLoginReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLoginReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLoginReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLoginReport(ctx, req.(*ReportPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopUsersReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopUsersReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopUsersReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopUsersReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopUsersReport(ctx, req.(*TopUsersReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchEvents",
			Handler:    _AnalyticsService_SearchEvents_Handler,
		},
		{
			MethodName: "GetRegistrationsReport",
			Handler:    _AnalyticsService_GetRegistrationsReport_Handler,
		},
		{
			MethodName: "GetLoginReport",
			Handler:    _AnalyticsService_GetLoginReport_Handler,
		},
		{
			MethodName: "GetTopUsersReport",
			Handler:    _AnalyticsService_GetTopUsersReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics.proto",
}
