// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SourceService string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsRequest) Reset() {
	*x = SearchEventsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsRequest) ProtoMessage() {}

func (x *SearchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsRequest.ProtoReflect.Descriptor instead.
func (*SearchEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *SearchEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SearchEventsRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *SearchEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SearchEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SearchEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AnalyticsEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalUserId string                 `protobuf:"bytes,2,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SourceService  string                 `protobuf:"bytes,4,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	OccurredAt     string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ReceivedAt     string                 `protobuf:"bytes,7,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyticsEvent) Reset() {
	*x = AnalyticsEvent{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEvent) ProtoMessage() {}

func (x *AnalyticsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEvent.ProtoReflect.Descriptor instead.
func (*AnalyticsEvent) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalyticsEvent) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *AnalyticsEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AnalyticsEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *AnalyticsEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *AnalyticsEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *AnalyticsEvent) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

type SearchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AnalyticsEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsResponse) Reset() {
	*x = SearchEventsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsResponse) ProtoMessage() {}

func (x *SearchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsResponse.ProtoReflect.Descriptor instead.
func (*SearchEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *SearchEventsResponse) GetEvents() []*AnalyticsEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPeriodRequest) Reset() {
	*x = ReportPeriodRequest{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPeriodRequest) ProtoMessage() {}

func (x *ReportPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPeriodRequest.ProtoReflect.Descriptor instead.
func (*ReportPeriodRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *ReportPeriodRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReportPeriodRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type RegistrationsReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationsReportItem) Reset() {
	*x = RegistrationsReportItem{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationsReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationsReportItem) ProtoMessage() {}

func (x *RegistrationsReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationsReportItem.ProtoReflect.Descriptor instead.
func (*RegistrationsReportItem) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationsReportItem) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *RegistrationsReportItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RegistrationsReportResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*RegistrationsReportItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationsReportResponse) Reset() {
	*x = RegistrationsReportResponse{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationsReportResponse) ProtoMessage() {}

func (x *RegistrationsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationsReportResponse.ProtoReflect.Descriptor instead.
func (*RegistrationsReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationsReportResponse) GetItems() []*RegistrationsReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LoginReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	SuccessCount  int64                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int64                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReportItem) Reset() {
	*x = LoginReportItem{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReportItem) ProtoMessage() {}

func (x *LoginReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReportItem.ProtoReflect.Descriptor instead.
func (*LoginReportItem) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReportItem) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *LoginReportItem) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *LoginReportItem) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type LoginReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LoginReportItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReportResponse) Reset() {
	*x = LoginReportResponse{}
	mi := &file_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReportResponse) ProtoMessage() {}

func (x *LoginReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReportResponse.ProtoReflect.Descriptor instead.
func (*LoginReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReportResponse) GetItems() []*LoginReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopUsersReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersReportRequest) Reset() {
	*x = TopUsersReportRequest{}
	mi := &file_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersReportRequest) ProtoMessage() {}

func (x *TopUsersReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersReportRequest.ProtoReflect.Descriptor instead.
func (*TopUsersReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *TopUsersReportRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TopUsersReportRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TopUsersReportRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopUserReportItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	EventsCount    int64                  `protobuf:"varint,2,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	LastActivityAt string                 `protobuf:"bytes,3,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopUserReportItem) Reset() {
	*x = TopUserReportItem{}
	mi := &file_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUserReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUserReportItem) ProtoMessage() {}

func (x *TopUserReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUserReportItem.ProtoReflect.Descriptor instead.
func (*TopUserReportItem) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TopUserReportItem) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *TopUserReportItem) GetEventsCount() int64 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

func (x *TopUserReportItem) GetLastActivityAt() string {
	if x != nil {
		return x.LastActivityAt
	}
	return ""
}

type TopUsersReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopUserReportItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersReportResponse) Reset() {
	*x = TopUsersReportResponse{}
	mi := &file_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersReportResponse) ProtoMessage() {}

func (x *TopUsersReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersReportResponse.ProtoReflect.Descriptor instead.
func (*TopUsersReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *TopUsersReportResponse) GetItems() []*TopUserReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\fanalytics.v1\"\xc6\x01\n" +
	"\x13SearchEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"\xf5\x01\n" +
	"\x0eAnalyticsEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10external_user_id\x18\x02 \x01(\tR\x0eexternalUserId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12%\n" +
	"\x0esource_service\x18\x04 \x01(\tR\rsourceService\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt\x12\x1f\n" +
	"\vreceived_at\x18\a \x01(\tR\n" +
	"receivedAt\"L\n" +
	"\x14SearchEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.analytics.v1.AnalyticsEventR\x06events\"9\n" +
	"\x13ReportPeriodRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"A\n" +
	"\x17RegistrationsReportItem\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"Z\n" +
	"\x1bRegistrationsReportResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.analytics.v1.RegistrationsReportItemR\x05items\"k\n" +
	"\x0fLoginReportItem\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x03R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x03R\vfailedCount\"J\n" +
	"\x13LoginReportResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.analytics.v1.LoginReportItemR\x05items\"Q\n" +
	"\x15TopUsersReportRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8a\x01\n" +
	"\x11TopUserReportItem\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12!\n" +
	"\fevents_count\x18\x02 \x01(\x03R\veventsCount\x12(\n" +
	"\x10last_activity_at\x18\x03 \x01(\tR\x0elastActivityAt\"O\n" +
	"\x16TopUsersReportResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.analytics.v1.TopUserReportItemR\x05items2\x89\x03\n" +
	"\x10AnalyticsService\x12U\n" +
	"\fSearchEvents\x12!.analytics.v1.SearchEventsRequest\x1a\".analytics.v1.SearchEventsResponse\x12f\n" +
	"\x16GetRegistrationsReport\x12!.analytics.v1.ReportPeriodRequest\x1a).analytics.v1.RegistrationsReportResponse\x12V\n" +
	"\x0eGetLoginReport\x12!.analytics.v1.ReportPeriodRequest\x1a!.analytics.v1.LoginReportResponse\x12^\n" +
	"\x11GetTopUsersReport\x12#.analytics.v1.TopUsersReportRequest\x1a$.analytics.v1.TopUsersReportResponseB2Z0github.com/Loop-company/http_gateway/proto;protob\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_analytics_proto_goTypes = []any{
	(*SearchEventsRequest)(nil),         // 0: analytics.v1.SearchEventsRequest
	(*AnalyticsEvent)(nil),              // 1: analytics.v1.AnalyticsEvent
	(*SearchEventsResponse)(nil),        // 2: analytics.v1.SearchEventsResponse
	(*ReportPeriodRequest)(nil),         // 3: analytics.v1.ReportPeriodRequest
	(*RegistrationsReportItem)(nil),     // 4: analytics.v1.RegistrationsReportItem
	(*RegistrationsReportResponse)(nil), // 5: analytics.v1.RegistrationsReportResponse
	(*LoginReportItem)(nil),             // 6: analytics.v1.LoginReportItem
	(*LoginReportResponse)(nil),         // 7: analytics.v1.LoginReportResponse
	(*TopUsersReportRequest)(nil),       // 8: analytics.v1.TopUsersReportRequest
	(*TopUserReportItem)(nil),           // 9: analytics.v1.TopUserReportItem
	(*TopUsersReportResponse)(nil),      // 10: analytics.v1.TopUsersReportResponse
}
var file_proto_analytics_proto_depIdxs = []int32{
	1,  // 0: analytics.v1.SearchEventsResponse.events:type_name -> analytics.v1.AnalyticsEvent
	4,  // 1: analytics.v1.RegistrationsReportResponse.items:type_name -> analytics.v1.RegistrationsReportItem
	6,  // 2: analytics.v1.LoginReportResponse.items:type_name -> analytics.v1.LoginReportItem
	9,  // 3: analytics.v1.TopUsersReportResponse.items:type_name -> analytics.v1.TopUserReportItem
	0,  // 4: analytics.v1.AnalyticsService.SearchEvents:input_type -> analytics.v1.SearchEventsRequest
	3,  // 5: analytics.v1.AnalyticsService.GetRegistrationsReport:input_type -> analytics.v1.ReportPeriodRequest
	3,  // 6: analytics.v1.AnalyticsService.GetLoginReport:input_type -> analytics.v1.ReportPeriodRequest
	8,  // 7: analytics.v1.AnalyticsService.GetTopUsersReport:input_type -> analytics.v1.TopUsersReportRequest
	2,  // 8: analytics.v1.AnalyticsService.SearchEvents:output_type -> analytics.v1.SearchEventsResponse
	5,  // 9: analytics.v1.AnalyticsService.GetRegistrationsReport:output_type -> analytics.v1.RegistrationsReportResponse
	7,  // 10: analytics.v1.AnalyticsService.GetLoginReport:output_type -> analytics.v1.LoginReportResponse
	10, // 11: analytics.v1.AnalyticsService.GetTopUsersReport:output_type -> analytics.v1.TopUsersReportResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
